// Mock data for products and user info
export const products = [
  {
    id: 1,
    name: "Premium Notebook",
    price: 1079,
    description: "A high-quality notebook with 200 pages of premium paper. Perfect for students and professionals.",
    category: "office-stationery",
    imageUrl: "/images/premium-notebook.jpg",
    stock: 50,
    featured: true,
  },
  {
    id: 2,
    name: "Gel Pen Set (10 pcs)",
    price: 746,
    description: "Set of 10 colorful gel pens with smooth writing experience. Water-resistant ink.",
    category: "office-stationery",
    imageUrl: "/images/gel-pen-set.jpg",
    stock: 100,
    featured: true,
  },
  {
    id: 3,
    name: "Desk Organizer",
    price: 2074,
    description: "Wooden desk organizer with multiple compartments for all your stationery needs.",
    category: "office-stationery",
    imageUrl: "/images/desk-organizer.jpg",
    stock: 25,
    featured: true,
  },
  {
    id: 4,
    name: "Sticky Notes Pack",
    price: 497,
    description: "Assorted sticky notes in different colors and sizes. Pack of 400 sheets.",
    category: "office-stationery",
    imageUrl: "/images/sticky-notes.jpg",
    stock: 150,
    featured: false,
  },
  {
    id: 5,
    name: "Art Sketchbook",
    price: 1244,
    description: "Artist-grade sketchbook with 120 pages of acid-free paper. Perfect for drawings and paintings.",
    category: "art-and-craft",
    imageUrl: "/images/sketchbook.jpg",
    stock: 40,
    featured: false,
  },
  {
    id: 6,
    name: "Mechanical Pencil Set",
    price: 995,
    description: "Set of 5 mechanical pencils with different lead sizes. Includes extra leads.",
    category: "office-stationery",
    imageUrl: "/images/mechanical-pencils.jpg",
    stock: 80,
    featured: false,
  },
  {
    id: 7,
    name: "Desk Lamp",
    price: 2489,
    description: "Adjustable LED desk lamp with 3 brightness levels and touch control.",
    category: "it-and-electrical",
    imageUrl: "/images/desk-lamp.jpg",
    stock: 20,
    featured: true,
  },
  {
    id: 8,
    name: "Calculator",
    price: 1327,
    description: "Scientific calculator with 240 functions and large display.",
    category: "it-and-electrical",
    imageUrl: "/images/calculator.jpg",
    stock: 35,
    featured: false,
  },
  {
    id: 9,
    name: "Highlighter Set",
    price: 663,
    description: "Set of 6 pastel highlighters with chisel tip for precise marking.",
    category: "office-stationery",
    imageUrl: "/images/highlighters.jpg",
    stock: 65,
    featured: false,
  },
  {
    id: 10,
    name: "File Folders (25 pcs)",
    price: 1161,
    description: "Set of 25 colorful file folders for organizing documents and papers.",
    category: "office-stationery",
    imageUrl: "/images/file-folders.jpg",
    stock: 45,
    featured: false,
  },
  {
    id: 11,
    name: "Ball Point Pen Set (12 pcs)",
    price: 299,
    description: "Set of 12 ball point pens in assorted colors with smooth writing experience.",
    category: "office-stationery",
    imageUrl: "/images/ballpoint-pens.jpg",
    stock: 120,
    featured: false,
  },
  {
    id: 12,
    name: "Fountain Pen Premium",
    price: 1599,
    description: "Premium fountain pen with gold-plated nib and elegant design.",
    category: "office-stationery",
    imageUrl: "/images/fountain-pen.jpg",
    stock: 15,
    featured: true,
  },
  {
    id: 13,
    name: "Marker Pen Set (8 colors)",
    price: 449,
    description: "Set of 8 permanent markers in different colors for presentations.",
    category: "office-stationery",
    imageUrl: "/images/marker-pens.jpg",
    stock: 85,
    featured: false,
  },
  {
    id: 14,
    name: "Cleaning Supplies Kit",
    price: 899,
    description: "Complete cleaning kit with detergents, brushes, and cloths.",
    category: "housekeeping-materials",
    imageUrl: "/images/cleaning-kit.jpg",
    stock: 30,
    featured: false,
  },
  {
    id: 15,
    name: "Coffee Beans Premium (1kg)",
    price: 1299,
    description: "Premium coffee beans for office pantry - rich aroma and taste.",
    category: "pantry-supplies",
    imageUrl: "/images/coffee-beans.jpg",
    stock: 25,
    featured: false,
  },
  {
    id: 16,
    name: "Bubble Wrap Roll (10m)",
    price: 599,
    description: "Protective bubble wrap for packaging fragile items safely.",
    category: "packaging-materials",
    imageUrl: "/images/bubble-wrap.jpg",
    stock: 40,
    featured: false,
  },
  {
    id: 17,
    name: "Corrugated Boxes (Pack of 10)",
    price: 799,
    description: "Strong corrugated boxes for shipping and storage needs.",
    category: "packaging-materials",
    imageUrl: "/images/corrugated-boxes.jpg",
    stock: 60,
    featured: false,
  },
  {
    id: 18,
    name: "Safety Helmet",
    price: 1299,
    description: "Industrial safety helmet with adjustable chin strap.",
    category: "safety-supplies",
    imageUrl: "/images/safety-helmet.jpg",
    stock: 25,
    featured: false,
  },
  {
    id: 19,
    name: "First Aid Kit",
    price: 899,
    description: "Complete first aid kit with essential medical supplies.",
    category: "safety-supplies",
    imageUrl: "/images/first-aid-kit.jpg",
    stock: 35,
    featured: false,
  },
  {
    id: 20,
    name: "Corporate Pen Set with Logo",
    price: 2499,
    description: "Premium pen set with custom corporate logo engraving.",
    category: "corporate-gifts",
    imageUrl: "/images/corporate-pen-set.jpg",
    stock: 20,
    featured: true,
  },
  {
    id: 21,
    name: "Branded Notebook Gift Set",
    price: 1999,
    description: "Elegant notebook gift set with company branding options.",
    category: "corporate-gifts",
    imageUrl: "/images/branded-notebook-set.jpg",
    stock: 30,
    featured: false,
  },
  {
    id: 22,
    name: "Acrylic Paint Set (24 colors)",
    price: 1599,
    description: "Professional acrylic paint set for artists and crafters.",
    category: "art-and-craft",
    imageUrl: "/images/acrylic-paint-set.jpg",
    stock: 15,
    featured: false,
  },
  {
    id: 23,
    name: "Craft Scissors Set",
    price: 699,
    description: "Set of precision craft scissors for detailed art work.",
    category: "art-and-craft",
    imageUrl: "/images/craft-scissors.jpg",
    stock: 45,
    featured: false,
  },
];

export const categories = [
  { id: 1, name: "office-stationery", displayName: "OFFICE STATIONERY" },
  { id: 2, name: "housekeeping-materials", displayName: "HOUSEKEEPING MATERIALS" },
  { id: 3, name: "pantry-supplies", displayName: "PANTRY SUPPLIES" },
  { id: 4, name: "it-and-electrical", displayName: "IT AND ELECTRICAL" },
  { id: 5, name: "packaging-materials", displayName: "PACKAGING MATERIALS" },
  { id: 6, name: "safety-supplies", displayName: "SAFETY SUPPLIES" },
  { id: 7, name: "corporate-gifts", displayName: "CORPORATE GIFTS" },
  { id: 8, name: "art-and-craft", displayName: "ART AND CRAFT" },
];

export const users = [
  {
    id: "user-001",
    name: "John Doe",
    email: "user@example.com",
    password: "password123", // In a real app, this would be hashed
    phone: "555-123-4567",
    address: {
      street: "123 Main St",
      city: "Anytown",
      state: "CA",
      zipCode: "90210",
      country: "United States"
    },
    createdAt: "2023-05-15T10:30:00.000Z"
  },
  {
    id: "user-002",
    name: "Jane Smith",
    email: "jane@example.com",
    password: "password123", // In a real app, this would be hashed
    phone: "555-987-6543",
    address: {
      street: "456 Oak Ave",
      city: "Somewhere",
      state: "NY",
      zipCode: "10001",
      country: "United States"
    },
    createdAt: "2023-03-22T14:15:00.000Z"
  }
];

export const orders = [
  {
    id: "order-001",
    orderNumber: "ORD-2023-0001",
    userId: "user-001",
    status: "Delivered",
    orderDate: "2023-07-15T09:30:00.000Z",
    deliveredDate: "2023-07-18T14:20:00.000Z",
    shippingAddress: {
      firstName: "John",
      lastName: "Doe",
      street: "123 Main St",
      city: "Anytown",
      state: "CA",
      zipCode: "90210",
      country: "United States"
    },
    paymentMethod: "Credit Card",
    items: [
      {
        id: 1,
        name: "Premium Notebook",
        price: 1079,
        quantity: 2,
        image: "/images/premium-notebook.jpg"
      },
      {
        id: 4,
        name: "Sticky Notes Pack",
        price: 497,
        quantity: 1,
        image: "/images/sticky-notes.jpg"
      }
    ],
    subtotal: 2655,
    shipping: 414,
    tax: 266,
    total: 3335
  },
  {
    id: "order-002",
    orderNumber: "ORD-2023-0002",
    userId: "user-002",
    status: "Shipped",
    orderDate: "2023-08-03T16:45:00.000Z",
    shippingAddress: {
      firstName: "Jane",
      lastName: "Smith",
      street: "456 Oak Ave",
      city: "Somewhere",
      state: "NY",
      zipCode: "10001",
      country: "United States"
    },
    paymentMethod: "PayPal",
    items: [
      {
        id: 7,
        name: "Desk Lamp",
        price: 2489,
        quantity: 1,
        image: "/images/desk-lamp.jpg"
      },
      {
        id: 9,
        name: "Highlighter Set",
        price: 663,
        quantity: 3,
        image: "/images/highlighters.jpg"
      }
    ],
    subtotal: 4478,
    shipping: 414,
    tax: 372,
    total: 5264
  },
  {
    id: "order-003",
    orderNumber: "ORD-2023-0003",
    userId: "user-001",
    status: "Processing",
    orderDate: "2023-08-20T11:15:00.000Z",
    shippingAddress: {
      firstName: "John",
      lastName: "Doe",
      street: "123 Main St",
      city: "Anytown",
      state: "CA",
      zipCode: "90210",
      country: "United States"
    },
    paymentMethod: "Credit Card",
    items: [
      {
        id: 3,
        name: "Desk Organizer",
        price: 2074,
        quantity: 1,
        image: "/images/desk-organizer.jpg"
      }
    ],
    subtotal: 2074,
    shipping: 414,
    tax: 207,
    total: 2695
  }
];
